name: Build

on:
  push:
    branches: ["main"]
    tags:
      - "v*"
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v3
      - name: uses Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./package.json
      - run: npm install
      - run: npm run lint
      - run: npm run build
      -
        name: 'Archive artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/no_search_engine-*.zip
          if-no-files-found: error
          overwrite: true
  release:
    if: github.ref_type == 'tag'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      -
        name: 'Download artifacts'
        uses: actions/download-artifact@v4
        with:
          name: dist
      -
        run: ls no_search_engine-*.zip
      -
        name: 'Create release'
        uses: softprops/action-gh-release@v2.3.2
        with:
          files: "no_search_engine-*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
